### PR TITLE
Fix millisecond to centisecond convertion

### PR DESCRIPTION
**Pull request by wangqr**
In original algorithm, the millisecond of the video frame is recorded when using ctrl+3/4. Ass only support centisecond, and the value is floor-ed to centisecond. In some cases this will shift the postion by 1 frame. This PR changes floor to round, to fix this issue. In case the last digit is 5, the value is always rounded up, so the next frame will be correctly included, but the previous frame is not. This only works with video framerate <= 100fps, but centisecond is only capable to be frame accurate for less than 100fps anyway.

This fix Aegisub/Aegisub#94

### CODE REVIEW

**Comment by wangqr** [comment]
PS: There are various bug fixes in [`wangqr:dev`](https://github.com/wangqr/Aegisub). Do I need to cherry-pick each of them and create a separate pull request, or you can just checkout my fork and do the cherry-pick yourself?

**Comment by wangqr** [comment]
Already merged

**Comment by tgoyne** [comment]
I went ahead and slurped up all the commits which applied cleanly without pulling in the cmake stuff and which looked obviously correct or reasonable. The remaining things there also mostly look great but need more than a cursory glance.

**Comment by CoffeeFlux** [comment]
Pretty sure this commit actually breaks things and wasn't tested properly. I can dig up old notes about it but the fix was too simplistic iirc, I'd really make sure to test this on a variety of files.

**Comment by wangqr** [comment]
A test case would be helpful. I actually uses this together with the align to hardsub (419386aaddec1b3383777572bfc23f4945dad4e2) on regular basis and see no problem.

**Pull request closed without merging**
