### PR TITLE
DataBlockCache: Fix crash in cache invalidation

### PR DESCRIPTION
**Pull request by scx**
DataBlockCache: Fix crash in cache invalidation.

Fixes undefined behavior e.g. when scrolling the audio view in spectrogram mode.

This patch is present in the official openSUSE packages.
http://download.opensuse.org/repositories/openSUSE:/Factory/standard/src/aegisub-3.2.2+git20180710-3.6.src.rpm

### CODE REVIEW

**Comment by wangqr** [comment]
I'm not quite sure what this PR does. But at least, `KillMacroBlock` will erase the cache from `age` list. If we do not step the iterator before calling the function, we'll end up with an invalid iterator.

**Comment by FichteFoll** [comment]
It fixes https://github.com/TypesettingTools/Aegisub/issues/33. (The same patch has been merged in the fork already.)

**Comment by wangqr** [comment]
Just confirmed this PR is invalid, by:
* Applying this PR
* Compile with `-D_GLIBCXX_DEBUG`
* Set `Spectrum > Cache memory max (MB)` to `2` (not sure why lachs0r said 10 but the minimum is 2) and restart Aegisub
* Load an audio, enable to `Spectrum analyser mode` and drag the scroll bar

And Aegisub will crash:
```
/usr/include/c++/9.1.0/debug/safe_iterator.h:597:
In function:
    __gnu_debug::_Safe_iterator<_Iterator, _Sequence, 
    std::bidirectional_iterator_tag>& __gnu_debug::_Safe_iterator<_Iterator, 
    _Sequence, std::bidirectional_iterator_tag>::operator--() [with 
    _Iterator = std::__cxx1998::_List_iterator<DataBlockCache<wxBitmap, 8, 
    AudioRendererBitmapCacheBitmapFactory>::MacroBlock*>; _Sequence = 
    std::__debug::list<DataBlockCache<wxBitmap, 8, 
    AudioRendererBitmapCacheBitmapFactory>::MacroBlock*, 
    std::allocator<DataBlockCache<wxBitmap, 8, 
    AudioRendererBitmapCacheBitmapFactory>::MacroBlock*> >]

Error: attempt to decrement a past-the-end iterator.

Objects involved in the operation:
    iterator "this" @ 0x0x7fffaff90370 {
      type = std::__cxx1998::_List_iterator<DataBlockCache<wxBitmap, 8, AudioRendererBitmapCacheBitmapFactory>::MacroBlock*> (mutable iterator);
      state = past-the-end;
      references sequence with type 'std::__debug::list<DataBlockCache<wxBitmap, 8, AudioRendererBitmapCacheBitmapFactory>::MacroBlock*, std::allocator<DataBlockCache<wxBitmap, 8, AudioRendererBitmapCacheBitmapFactory>::MacroBlock*> >' @ 0x0x55ba35a4e038
    }
[1]    3417 abort (core dumped)  ./aegisub
```

**Comment by wangqr** [comment]
Ok I see that `it` is a reverse_iterator. In this case, `it` should always point to the rbegin() (so its `.base()` is pointing to the one-past-the-end) and should never increase. And in this PR we are actually erasing every other block from the end and sometimes `it` just go past `rend()`.

**Pull request merged**
