### PR TITLE
Fix system luajit

### PR DESCRIPTION
**Pull request by scx**
Fix system LuaJIT.

http://web.archive.org/web/20161027172024/http://devel.aegisub.org/ticket/1904
http://web.archive.org/web/20160628055359/http://devel.aegisub.org/ticket/1913
http://web.archive.org/web/20161027172029/http://devel.aegisub.org/ticket/1922
https://github.com/gentoo/gentoo/blob/e2087ed19aa3327eb00833f64e5bf315d43816fa/media-video/aegisub/files/3.2.2_p20160518/aegisub-3.2.2_p20160518-fix-system-luajit-build.patch

Similar patches are present in the official Debian, Ubuntu, Mageia and Gentoo packages.
http://deb.debian.org/debian/pool/main/a/aegisub/aegisub_3.2.2+dfsg-4.debian.tar.xz
http://archive.ubuntu.com/ubuntu/pool/universe/a/aegisub/aegisub_3.2.2+dfsg-4build1.debian.tar.xz
http://distrib-coffee.ipsl.jussieu.fr/pub/linux/Mageia/distrib/cauldron/SRPMS/core/release/aegisub-3.2.2-14.git20180730.7.mga8.src.rpm
https://github.com/gentoo/gentoo/blob/be23ef21ed508c8e580f3ee8f302ce2abc5c3fbe/media-video/aegisub

### CODE REVIEW

**Comment by wangqr** [comment]
The current `./configure` already has a option to use the system LuaJIT:
```
./configure --with-system-luajit
```
It will [check whether the system LuaJIT is usable](https://github.com/Aegisub/Aegisub/blob/2cb92a5f74634764ff5aac7e3ad0d647f98142af/configure.ac#L405-L414), and fallback to bundled LuaJIT in case of failure. You can also manually override the result of the check by
```
./configure --with-system-luajit agi_cv_luajit_is_52=yes  # NOT RECOMMENDED
```
But this will cause problem and you are responsible for your decision.

The test checks if LuaJIT is compiled with `LUAJIT_ENABLE_LUA52COMPAT`, and most system-provided LuaJIT don't have that feature enabled.

**Comment by scx** [comment]
> The current `./configure` already has a option to use the system LuaJIT:
> 
> ```
> ./configure --with-system-luajit
> ```

Yeah, I know that.

> It will [check whether the system LuaJIT is usable](https://github.com/Aegisub/Aegisub/blob/2cb92a5f74634764ff5aac7e3ad0d647f98142af/configure.ac#L405-L414), and fallback to bundled LuaJIT in case of failure.

But does it really work? If I good remember, there were some problems with it. Doesn't it still use bundled lua even if the `--with-system-luajit` argument was specified and an acceptable system LuaJIT was found?
https://github.com/Aegisub/Aegisub/blob/2cb92a5f74634764ff5aac7e3ad0d647f98142af/header.mk#L16

And this one looks suspicious for me:
https://github.com/Aegisub/Aegisub/blob/2cb92a5f74634764ff5aac7e3ad0d647f98142af/Makefile.inc.in#L82
https://github.com/Aegisub/Aegisub/blob/2cb92a5f74634764ff5aac7e3ad0d647f98142af/Makefile.inc.in#L100
Or maybe I am missing something?

> You can also manually override the result of the check by
> 
> ```
> ./configure --with-system-luajit agi_cv_luajit_is_52=yes  # NOT RECOMMENDED
> ```
> 
> But this will cause problem and you are responsible for your decision.

That's why I want to avoid that.

> The test checks if LuaJIT is compiled with `LUAJIT_ENABLE_LUA52COMPAT`, and most system-provided LuaJIT don't have that feature enabled.

I know about it and that's why I want to make it fully optional.
```
ifeq (no, $(SYSTEM_LUAJIT))
// use bundled LuaJIT
else
// use system LuaJIT
endif
```

As for my package, I compiled LuaJIT with the `-DLUAJIT_ENABLE_LUA52COMPAT` option:
https://github.com/scx/aegisub-flatpak/blob/afa7a639606a385091d43921279cad151f125340/luajit.yaml#L213-L218
https://github.com/scx/aegisub-flatpak/blob/afa7a639606a385091d43921279cad151f125340/luajit-LUA52COMPAT.patch

**Comment by aniolm9** [comment]
I would also appreciate being able to use the system LuaJIT. I think it's worth mention the Debian Bug [#892765](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892765) that allows Aegisub to build in more architectures. I'll submit a patch in this PR later this evening.

**Comment by wangqr** [comment]
> https://github.com/Aegisub/Aegisub/blob/2cb92a5f74634764ff5aac7e3ad0d647f98142af/header.mk#L16

Agree. This one should be removed if we are using system luajit

> 
> And this one looks suspicious for me:
> 
> https://github.com/Aegisub/Aegisub/blob/2cb92a5f74634764ff5aac7e3ad0d647f98142af/Makefile.inc.in#L82
> 
> https://github.com/Aegisub/Aegisub/blob/2cb92a5f74634764ff5aac7e3ad0d647f98142af/Makefile.inc.in#L100
> 

Actually `LUAJIT_CFLAGS` and `LUAJIT_LIBS` are [set by `pkg-config` by default](https://github.com/Aegisub/Aegisub/blob/2cb92a5f74634764ff5aac7e3ad0d647f98142af/configure.ac#L393) and we only override them if [not using system luajit](https://github.com/Aegisub/Aegisub/blob/2cb92a5f74634764ff5aac7e3ad0d647f98142af/configure.ac#L428). `BIN_LUA` (which comes from `LUA`) also prefer system binary if exist.

As for the override in `BUILD_DARWIN`, it seems that they gave the bundled luajit shared object a different name on Mac and doesn't changed that after adding the option to use system lua: https://github.com/Aegisub/Aegisub/commit/63f4bf1beb824ab95c1fa281253c437cd8af5c4d#diff-3178fdcd5fb8b056c1fe69b33cde4fab

**Comment by aniolm9** [comment]
It seems that in Debian it won't be possible to use a system library from APT as they are not compiled using Lua 5.2, so I'll stay with the vendor version.

**Pull request closed without merging**
